// Cities data organized by country shortcode
export const CITIES = {
  uk: [
    "London",
    "Manchester",
    "Birmingham",
    "Liverpool",
    "Leeds",
    "Glasgow",
    "Edinburgh",
    "Bristol",
    "Cardiff",
    "Belfast",
    "Newcastle",
    "Nottingham",
    "Sheffield",
    "Leicester",
    "Coventry",
    "Bradford",
    "Kingston upon Hull",
    "Stoke-on-Trent",
    "Wolverhampton",
    "Plymouth",
  ],
  us: [
    "New York",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "Charlotte",
    "San Francisco",
    "Indianapolis",
    "Seattle",
    "Denver",
    "Boston",
  ],
  ca: [
    "Toronto",
    "Vancouver",
    "Montreal",
    "Calgary",
    "Edmonton",
    "Ottawa",
    "Winnipeg",
    "Quebec City",
    "Hamilton",
    "Kitchener",
    "London",
    "Victoria",
    "Halifax",
    "Oshawa",
    "Windsor",
    "Saskatoon",
    "Regina",
    "Sherbrooke",
    "St. John's",
    "Barrie",
  ],
  ie: [
    "Dublin",
    "Cork",
    "Limerick",
    "Galway",
    "Waterford",
    "Drogheda",
    "Kilkenny",
    "Wexford",
    "Sligo",
    "Clonmel",
    "Tralee",
    "Ennis",
    "Carlow",
    "Naas",
    "Athlone",
    "Letterkenny",
    "Tullamore",
    "Killarney",
    "Arklow",
    "New Ross",
  ],
  au: [
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Gold Coast",
    "Newcastle",
    "Canberra",
    "Sunshine Coast",
    "Wollongong",
    "Hobart",
    "Geelong",
    "Townsville",
    "Cairns",
    "Toowoomba",
    "Darwin",
    "Ballarat",
    "Bendigo",
    "Albury",
    "Launceston",
  ],
} as const;

export type CityData = {
  name: string;
  slug: string;
  countryShortcode: string;
};

// Helper function to generate slug from city name
export const generateSlug = (name: string): string => {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
};
